
name: Cucumber7ThreadSafe

permissions:
  contents: write
  pages: write 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run test with maven
      run: mvn clean compile test
      
    - name: Install Allure commandline
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
        tar -zxvf allure-2.24.0.tgz
        sudo mv allure-2.24.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report  # Generate Allure report


        
    - name: Deploy Allure report to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        # Clone the gh-pages branch
        git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages || git clone https://github.com/${{ github.repository }} gh-pages
    
        # Navigate to the gh-pages directory
        cd gh-pages
    
        # Clear any changes or files that might cause conflicts
        git reset --hard
    
        # Copy Allure report to the gh-pages branch
        cp -r /allure-report/* .
    
        # Configure Git
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
    
        # Commit and push the changes
        git add .
        git commit -m "Deploy Allure report"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages



