name: Cucumber7ThreadSafe

permissions:
  contents: write
  pages: write 

on:
  push:
    branches:
      - master  # Trigger this action on push to the 'master' branch
  workflow_dispatch:  # Allow manual triggers of the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Run test with Maven
      - name: Run test with maven
        run: mvn clean compile test

      # Install Allure commandline
      - name: Install Allure commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxvf allure-2.24.0.tgz
          sudo mv allure-2.24.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      # Generate Allure report
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report  # Generate the report

      # Deploy Allure report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        if: github.ref == 'refs/heads/master'  # Only deploy from the 'master' branch
        run: |
          # Clean up any previous gh-pages directory if it exists
          if [ -d "gh-pages" ]; then
            rm -rf gh-pages
          fi

          # Clone the gh-pages branch
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages || git clone https://github.com/${{ github.repository }} gh-pages

          # Copy Allure report to the gh-pages directory
          cp -r allure-report/* gh-pages/

          # Navigate to the gh-pages directory
          cd gh-pages

          # Configure Git
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Commit and push the Allure report to the gh-pages branch
          git add .
          git commit -m "Deploy Allure report"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
