
name: Cucumber7ThreadSafe

permissions:
  contents: write
  pages: write 

on:
  push:
    branches:
      - master  # Trigger this action on push to the 'main' branch
  workflow_dispatch:  # Allow manual triggers of the action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java and Maven (if not already configured)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # Install dependencies and generate Allure report using Maven
      - name: Build and generate Allure report
        run: |
          mvn clean compile test
          mvn allure:serve

      # Deploy Allure report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        if: github.ref == 'refs/heads/master'  # Only deploy from the 'main' branch
        run: |
          # Clean up any previous gh-pages directory if it exists
          if [ -d "gh-pages" ]; then
            rm -rf gh-pages
          fi

          # Clone the gh-pages branch
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages || git clone https://github.com/${{ github.repository }} gh-pages

          # Copy Allure report to the gh-pages directory
          cp -r allure-report/* gh-pages/

          # Navigate to the gh-pages directory
          cd gh-pages

          # Configure Git
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Commit and push the Allure report to the gh-pages branch
          git add .
          git commit -m "Deploy Allure report"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
